### ISSUE TITLE
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

### ISSUE THREAD

**Issue by lnlwd** [tjworks/angoose#28]
While trying to load a Model in an Angular controller i get this error.

>Failed to load resource: the server responded with a status of 500 (Internal Server Error)
"TypeError: Cannot convert undefined or null to object<br> &nbsp; &nbsp;at E:\Documents\MyOpenSource\angular2\node_modules\angoose\lib\Pipeline.js:212:31<br> &nbsp; &nbsp;at Array.forEach (native)<br> &nbsp; &nbsp;at Function.Pipeline.execute (E:\Documents\MyOpenSource\angular2\node_modules\angoose\lib\Pipeline.js:211:64)<br> &nbsp; &nbsp;at accept (E:\Documents\MyOpenSource\angular2\node_modules\angoose\lib\Pipeline.js:308:14)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (E:\Documents\MyOpenSource\angular2\node_modules\express\lib\router\layer.js:82:5)<br> &nbsp; &nbsp;at next (E:\Documents\MyOpenSource\angular2\node_modules\express\lib\router\route.js:110:13)<br> &nbsp; &nbsp;at Route.dispatch (E:\Documents\MyOpenSource\angular2\node_modules\express\lib\router\route.js:91:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (E:\Documents\MyOpenSource\angular2\node_modules\express\lib\router\layer.js:82:5)<br> &nbsp; &nbsp;at E:\Documents\MyOpenSource\angular2\node_modules\express\lib\router\index.js:267:22<br> &nbsp; &nbsp;at param (E:\Documents\MyOpenSource\angular2\node_modules\express\lib\router\index.js:340:14) "

**Comment by Harriet92** [comment]
Hi, how did you resolve the problem?
